Task.create(name: 'Write a book')
Task.create(name: 'Buy battery')
Task.create(name: 'Buy air fryer')
Task.create(name: 'Buy a house')
Task.create(name: 'Buy a puppy')
Task.create(name: 'Watch a movie')
Task.create(name: 'Pick the winner')
Task.create(name: 'Write an article')
Task.create(name: 'Develop a webapp')
Task.create(name: 'Record a video')
Task.create(name: 'Drive a jeep')
Task.create(name: 'Delete the bucket list')
Task.create(name: 'Search for fish')
Task.create(name: 'Walk on sand')
Task.create(name: 'Ride a motorcycle')
Task.create(name: 'Check the binoculor')
Task.create(name: 'Sell energy drink')
Task.create(name: 'Make coffee')
Task.create(name: 'Turn off light')
Task.create(name: 'Search for bulb')
Task.create(name: 'Get a haircut')
Task.create(name: 'Recharge battery')
Task.create(name: 'Chop wood to make fire')
Task.create(name: 'Fly over island')
Task.create(name: 'Read a book')